# SQLite version 3.x
#   gem install sqlite3-ruby (not necessary on OS X Leopard)
development:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: ImHo_dev
  pool: 5
  username: root
  password:
  host: 127.0.0.1

test:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: ImHo_test
  pool: 5
  username: root
  password:
  host: 127.0.0.1

production:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: ImHo
  pool: 5
  username: root
  password:
  host: 127.0.0.1